version: 3

project:
  id: camunda/camunda-modeler
  labels:
  - camunda-modeler
  - modeler
  policy: Camunda8 Distribution
  url: https://github.com/camunda/camunda-modeler

paths:
  exclude:
  - ./resources
