name: ADD_TO_PROJECT

on:
  issues:
    types:
      - opened
      - transferred
      - labeled
  pull_request:
    types:
      - opened
      - labeled

jobs:
  exec:
    name: Add issue to project
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false
          secrets: |
            secret/data/products/desktop-modeler/ci/ADD_TO_PROJECT_PAT ADD_TO_PROJECT_PAT;
      - uses: actions/add-to-project@v1.0.0
        with:
          project-url: ${{ secrets.CONNECTORS_PROJECT_URL }}
          github-token: ${{ steps.secrets.outputs.ADD_TO_PROJECT_PAT }}
          labeled: connectors
