name: MERGE_MAIN_TO_DEVELOP
on:
  push:
    branches:
    - "main"

jobs:
  merge_main_to_develop:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout develop
      uses: actions/checkout@v5
      with:
        ref: develop
        fetch-depth: 0
    - name: Merge main to develop and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git merge -m 'chore: merge main to develop' --no-edit origin/main
        git push

  post_failure:
    name: Notify failure
    needs: merge_main_to_develop
    if: failure()
    runs-on: ubuntu-latest
    steps:
    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v3.0.0
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        exportEnv: false
        secrets: |
          secret/data/products/desktop-modeler/ci/slack_integration SLACK_CHANNEL_ID;
          secret/data/products/desktop-modeler/ci/slack_integration SLACK_BOT_TOKEN;
    - name: Notify on Slack if merge fails
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: ${{ steps.secrets.outputs.SLACK_BOT_TOKEN }}
        payload: |
          channel: ${{ steps.secrets.outputs.SLACK_CHANNEL_ID }}
          text: "Automatic merge of <https://github.com/${{ github.repository }}/tree/${{ github.ref }}|${{ github.ref }}> to <https://github.com/${{ github.repository }}/tree/develop|${{ github.repository }}#develop> failed."
